version: '3.9'

services:
  clubmanager-backend:
    image: 'clubmanager:latest'
    container_name: 'clubmanager-backend'
    build:
      context: ./backend/clubmanager
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - clubmanager-network

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    networks:
      - clubmanager-network



networks:
  clubmanager-network:
    driver: bridge